import { PROVINCES } from "./geo";
import {
  loadDistricts,
  pointInPolygon,
  representativePoint,
  type Position,
} from "./geography";
import type { EventCandidateDoc } from "./types";

/**
 * Geographic sanity checks for event coordinates.
 *
 * Checks run from the outside in — country box, then the four provinces, then
 * the claimed province, then the claimed district, then the precision
 * semantics. Reporting which layer failed says how deep the problem goes: a
 * failure at layer 1 is a broken coordinate, at layer 4 a label/geometry
 * disagreement, at layer 5 a precision that misrepresents what is known.
 *
 * This exists because event coordinates were once generated by jittering around
 * hand-written centroids, which put 18% of them in the Gulf of Thailand and
 * left only 9% inside the district they claimed. Nothing should reach the
 * database in that state again.
 */

export interface PlacementFailure {
  layer: 1 | 2 | 3 | 4 | 5;
  check: string;
  eventId: string;
  detail: string;
}

export interface PlacementReport {
  total: number;
  failures: PlacementFailure[];
  /** Points landing inside more than one district — simplification overlap. */
  borderOverlaps: number;
  ok: boolean;
}

/** Generous box around Thailand; anything outside is a broken coordinate. */
const THAILAND_BBOX = { minLng: 97, maxLng: 106, minLat: 5, maxLat: 21 };

/** Tolerance in degrees when comparing a stored point to a computed one. */
const POINT_EPSILON = 1e-9;

export function validateEventPlacement(events: EventCandidateDoc[]): PlacementReport {
  const districts = loadDistricts();
  const ddpmByCode = new Map(PROVINCES.map((p) => [p.code, p.ddpmCode]));

  const failures: PlacementFailure[] = [];
  let borderOverlaps = 0;

  const fail = (layer: PlacementFailure["layer"], check: string, eventId: string, detail: string) =>
    failures.push({ layer, check, eventId, detail });

  for (const e of events) {
    const id = e._id;
    const coords = e.location.geo?.coordinates;

    // Layer 1 — is it even a coordinate, and on the right continent?
    if (!Array.isArray(coords) || coords.length !== 2 || !coords.every(Number.isFinite)) {
      fail(1, "finite coordinate", id, `coordinates=${JSON.stringify(coords)}`);
      continue;
    }
    const pt = coords as Position;
    const [lng, lat] = pt;
    if (
      lng < THAILAND_BBOX.minLng ||
      lng > THAILAND_BBOX.maxLng ||
      lat < THAILAND_BBOX.minLat ||
      lat > THAILAND_BBOX.maxLat
    ) {
      fail(1, "inside Thailand bbox", id, `[${lng}, ${lat}]`);
      continue;
    }

    // Layers 2-4 all resolve against the district polygons rather than the
    // province ones. Districts are the finest geometry available and they tile
    // their province exactly, so "inside some district" is the sharpest
    // definition of on-land-and-in-scope we have. Testing province containment
    // separately would only compare two independently simplified outlines and
    // flag the gaps between them — a rendering artifact, not a data defect.
    // The district-to-province relation comes from `province_code` in the
    // source data, which is authoritative.
    const containingDistricts = districts.filter(
      (d) =>
        lng >= d.bbox[0] && lng <= d.bbox[2] && lat >= d.bbox[1] && lat <= d.bbox[3] &&
        pointInPolygon(pt, d.geometry),
    );
    if (containingDistricts.length > 1) borderOverlaps++;

    // Layer 2 — on land, inside one of the districts in scope.
    if (containingDistricts.length === 0) {
      fail(2, "on land in the four provinces", id, `[${lng}, ${lat}] is in the sea or out of scope`);
      continue;
    }

    // Layer 3 — that district belongs to the province the record claims.
    const claimedDdpm = ddpmByCode.get(e.location.provinceCode);
    if (!containingDistricts.some((d) => d.provinceCode === claimedDdpm)) {
      fail(
        3,
        "inside the claimed province",
        id,
        `claims ${e.location.province}, point is in ${containingDistricts
          .map((d) => d.provinceNameTh)
          .join("/")}`,
      );
      continue;
    }

    // Layer 4 — inside the district the record claims.
    const claimed = containingDistricts.find((d) => d.nameTh === e.location.district);
    if (!claimed) {
      fail(
        4,
        "inside the claimed district",
        id,
        `claims อ.${e.location.district}, point is in ${containingDistricts
          .map((d) => d.nameTh)
          .join("/")}`,
      );
      continue;
    }

    // Layer 5 — does the coordinate mean what the precision says it means?
    // A district-level geocode resolves the whole district to one point, so the
    // stored coordinate must be exactly that point, not a position inside it.
    const precision = e.location.geo_precision;
    if (precision === "district" || precision === "province" || precision === "unknown") {
      const expected = representativePoint(claimed.geometry);
      const drift = Math.hypot(pt[0] - expected[0], pt[1] - expected[1]);
      if (drift > POINT_EPSILON) {
        fail(
          5,
          "coarse precision uses the representative point",
          id,
          `precision=${precision} but point differs from อ.${claimed.nameTh} representative point by ${drift.toFixed(6)}°`,
        );
      }
    }
  }

  return { total: events.length, failures, borderOverlaps, ok: failures.length === 0 };
}

/** Human-readable summary, grouped by the layer that failed. */
export function formatPlacementReport(report: PlacementReport): string {
  const lines: string[] = [];
  const LAYER_NAME: Record<number, string> = {
    1: "coordinate is finite and inside Thailand",
    2: "on land within the four provinces",
    3: "inside the claimed province",
    4: "inside the claimed district",
    5: "precision matches how the point was derived",
  };

  for (let layer = 1; layer <= 5; layer++) {
    const hits = report.failures.filter((f) => f.layer === layer);
    const status = hits.length === 0 ? "PASS" : `FAIL (${hits.length})`;
    lines.push(`  ${layer}. ${LAYER_NAME[layer].padEnd(46)} ${status}`);
    // Show a few offenders so the failure is actionable, not just a count.
    for (const f of hits.slice(0, 3)) lines.push(`       ${f.eventId}: ${f.detail}`);
    if (hits.length > 3) lines.push(`       … and ${hits.length - 3} more`);
  }

  if (report.borderOverlaps > 0) {
    lines.push(
      `  note: ${report.borderOverlaps} point(s) fall inside two districts at once — ` +
        `adjacent polygons overlap slightly because each is simplified independently.`,
    );
  }
  return lines.join("\n");
}
