/** Audit, enrich, and add verified southern security incidents for 10-16 May 2026. */
import { createHash, randomUUID } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { MongoClient } from "mongodb";
import type { EventCandidateDoc, IngestionRunDoc, RawRecordDoc, SourceRegistryDoc } from "../src/lib/types";

function loadEnv(): void { const path = resolve(process.cwd(), ".env"); if (!existsSync(path)) return; for (const line of readFileSync(path, "utf8").split(/\r?\n/)) { const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/); if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^(['"])(.*)\1$/, "$2"); } }
loadEnv();
const SOURCE_ID = "src_manual_research";
const WINDOW_ID = "verified-window-2026-05-10-to-16";
const DEFAULT_URI = "mongodb://root:changeme@localhost:27017/palantir_th?authSource=admin";
const SBPAC = "https://opendata.sbpac.go.th/API/relief_01_01.aspx";

const update = {
  id: "evt_a64ccf65014ab4bfc81b3a40",
  urls: ["https://www.southpeace.go.th/?p=170504", "https://thainews.prd.go.th/thainews/news/view/2013203/?bid=1", "https://www.tnews.co.th/social/social-news/650171", "https://www.isranews.org/article/south-news/south-slide/147105-officershoot.html", SBPAC],
  set: {
    "time.start": new Date("2026-05-11T10:30:00+07:00"), "time.precision": "minute", "location.place": "ถนนทางหลวงหมายเลข 4057 ช่วงก่อนถึงสะพานน้ำขาว บ้านไม้ฝาด หมู่ 8 ตำบลกายูคละ อำเภอแว้ง จังหวัดนราธิวาส", "location.geo": null, "location.geo_precision": "unknown",
    "event.type": "explosion", "event.title": "ลอบวางระเบิดรถทหารพรานบนถนน 4057 บ้านไม้ฝาด", "event.rawType": "ลอบวางระเบิดแสวงเครื่องโจมตีขบวนรถทหารพราน",
    "event.summary": "คนร้ายลอบวางระเบิดถังแก๊สหนักประมาณ 50 กิโลกรัมซุกในท่อลอดใต้ถนนทางหลวง 4057 แล้วจุดชนวนใส่รถปิดท้ายขบวนของชุดปฏิบัติการทหารพรานที่ 1106 ซึ่งกำลังเดินทางรับคณะผู้บังคับบัญชาตรวจเยี่ยมหน่วย รถกระบะพลิกหงาย ส.อ.อดิศร คำบุญช่วย เสียชีวิต จ.ส.อ.คมกฤษ ฤทธิ์ธาภัย และ อส.ทพ.พงศกร แสนบุญมี บาดเจ็บ อีกทั้งนายนิพัฐพนธ์ เตียวเจริญธรรม และนายศักดินันท์ อาแว ซึ่งเป็นประชาชนที่ผ่านทางได้รับบาดเจ็บ",
    severity: 5, verification: "verified", confidence: 99, casualties: { killed: 1, injured: 4 }, actors: ["กลุ่มคนร้ายไม่ทราบจำนวนผู้ลอบวางและจุดชนวนระเบิด"], targets: ["รถและกำลังพลชุดปฏิบัติการทหารพรานที่ 1106 ฉก.ทพ.11", "ขบวนผู้บังคับบัญชากองกำลังทหารพรานจังหวัดชายแดนภาคใต้", "ประชาชนผู้ใช้ทาง"],
    "attributes.killed_security": 1, "attributes.injured_security": 2, "attributes.injured_civilian": 2, "attributes.explosive_container": "ถังแก๊ส", "attributes.explosive_weight_kg": 50, "attributes.location_text_precision": "road_village_landmark",
  } as Record<string, unknown>,
};

const additions: EventCandidateDoc[] = [
  {
    _id: "evt_verified_20260513_dusongyo_as_shooting", source_id: SOURCE_ID, raw_record_id: "raw_verified_20260513_dusongyo_as_shooting",
    time: { start: new Date("2026-05-13T07:20:00+07:00"), precision: "minute" },
    location: { province: "นราธิวาส", provinceCode: "narathiwat", district: "จะแนะ", subdistrict: "ดุซงญอ", place: "ถนนสายดุซงญอ–กาแย บริเวณบ้านกาแย หมู่ 5 ตำบลดุซงญอ อำเภอจะแนะ จังหวัดนราธิวาส", geo: null, geo_precision: "unknown" },
    event: { type: "shooting", title: "ประกบยิง อส.ชคต.ดุซงญอ ขณะกลับจากปฏิบัติหน้าที่", rawType: "ลอบยิงสมาชิกชุดคุ้มครองตำบล", summary: "คนร้ายไม่ทราบจำนวนขี่รถจักรยานยนต์ยามาฮ่า ฟีลาโน สีชมพู ไม่ทราบทะเบียน ตามประกบนายอาฟันนี เจ๊ะเต๊ะ อายุ 40 ปี สมาชิก อส.ชคต.ดุซงญอ ขณะขี่รถจักรยานยนต์จากฐานกลับบ้านพัก แล้วใช้อาวุธปืนไม่ทราบชนิดยิงก่อนหลบหนี ผู้เสียหายถูกยิงต้นขาขวา 3 แผล สะโพกขวา 1 แผล และนิ้วมือขวา 1 แผล รวม 5 แผล ส่งจากโรงพยาบาลจะแนะไปรักษาต่อที่โรงพยาบาลนราธิวาสราชนครินทร์" },
    severity: 4, verification: "verified", confidence: 98, casualties: { killed: 0, injured: 1 }, actors: ["มือปืนไม่ทราบจำนวน ใช้รถจักรยานยนต์ยามาฮ่า ฟีลาโน สีชมพู"], targets: ["นายอาฟันนี เจ๊ะเต๊ะ สมาชิก อส.ชคต.ดุซงญอ"], corroborating_sources: [SOURCE_ID], media: [],
    attributes: { research_batch: WINDOW_ID, location_address: "ถนนสายดุซงญอ–กาแย บริเวณบ้านกาแย หมู่ 5 ตำบลดุซงญอ อำเภอจะแนะ จังหวัดนราธิวาส", location_text_precision: "road_village", source_count: 2, source_url_1: "https://www.southpeace.go.th/?p=170791", source_url_2: "https://www.isranews.org/article/south-news/south-slide/147105-officershoot.html", victim_wound_count: 5 },
    unreported: ["coordinates", "weapon_type", "perpetrator_identity"],
  },
  {
    _id: "evt_verified_20260515_panare_halal_industrial_bombing", source_id: SOURCE_ID, raw_record_id: "raw_verified_20260515_panare_halal_industrial_bombing",
    time: { start: new Date("2026-05-15T22:45:00+07:00"), precision: "minute" },
    location: { province: "ปัตตานี", provinceCode: "pattani", district: "ปะนาเระ", subdistrict: "บ้านน้ำบ่อ", place: "อาคารศูนย์บริการเบ็ดเสร็จครบวงจร ภายในพื้นที่ส่งเสริมอุตสาหกรรมอาหารฮาลาล บ้านท่าสู หมู่ 3 ตำบลบ้านน้ำบ่อ อำเภอปะนาเระ จังหวัดปัตตานี", geo: null, geo_precision: "unknown" },
    event: { type: "explosion", title: "กลุ่มติดอาวุธวางระเบิดหลายลูกในพื้นที่อุตสาหกรรมฮาลาลปัตตานี", rawType: "บุกขับไล่ รปภ. และวางระเบิดแสวงเครื่องทำลายอาคาร", summary: "ชายปกปิดใบหน้า 4 คนบุกเข้าในพื้นที่ บังคับเจ้าหน้าที่รักษาความปลอดภัยให้ออกจากอาคาร ก่อนมีเสียงระเบิด 3 ครั้ง ไม่มีผู้เสียชีวิตหรือบาดเจ็บ เจ้าหน้าที่ใช้โดรน สุนัขทหาร และ EOD ตรวจพื้นที่ในวันที่ 19 พ.ค. พบระเบิดแสวงเครื่องบรรจุกล่องเหล็กและตั้งเวลาด้วยดิจิทัลไทม์เคาท์ดาวน์รวม 10 ลูกในอาคาร 3 หลัง รายงานยืนยันระเบิดทำงานแล้วอย่างน้อย 3 ลูกและเก็บกู้ระเบิดด้าน 2 ลูก แต่ไม่ได้แจกแจงสถานะอีก 5 ลูกอย่างชัดเจน อาคารอย่างน้อย 2 หลังได้รับความเสียหาย" },
    severity: 5, verification: "verified", confidence: 98, casualties: { killed: 0, injured: 0 }, actors: ["ชายปกปิดใบหน้า 4 คน"], targets: ["พื้นที่ส่งเสริมอุตสาหกรรมอาหารฮาลาลจังหวัดปัตตานี", "อาคารศูนย์บริการเบ็ดเสร็จครบวงจร 3 หลัง", "เจ้าหน้าที่รักษาความปลอดภัย"], corroborating_sources: [SOURCE_ID], media: [],
    attributes: { research_batch: WINDOW_ID, location_address: "อาคารศูนย์บริการเบ็ดเสร็จครบวงจร ภายในพื้นที่ส่งเสริมอุตสาหกรรมอาหารฮาลาล บ้านท่าสู หมู่ 3 ตำบลบ้านน้ำบ่อ อำเภอปะนาเระ จังหวัดปัตตานี", location_text_precision: "named_site_village", source_count: 3, source_url_1: "https://www.southpeace.go.th/?p=171219", source_url_2: "https://www.isranews.org/article/south-news/other-news/147034-halalpanarae.html", source_url_3: "https://www.antifakenewscenter.com/news/activity/โรงงานในนิคมอุตสาหกรรมฮาลาล-ปัตตานี-เกิดเหตุระเบิดและเพลิงไหม้-ควันพวยพุ่งเป็นวงกว้างกลางดึก", explosive_device_count: 10, exploded_device_count_minimum: 3, unexploded_device_count: 2, device_status_unresolved_count: 5, affected_building_count_minimum: 2, initiation: "digital_countdown_timer", explosive_fill: "ANFO", device_count_discrepancy: "พาดหัว Isranews ระบุ 12 ลูก แต่รายละเอียดการตรวจภายในระบุรวม 10 ลูก จึงใช้ 10 ตามรายละเอียด", image_misinformation_note: "ศูนย์ต่อต้านข่าวปลอมยืนยันว่าภาพควันไฟที่เผยแพร่บางภาพเป็นภาพเหตุอื่น ไม่ใช่ภาพเหตุการณ์นี้" },
    unreported: ["coordinates", "damage_value", "perpetrator_identity"],
  },
];

function hash(value: unknown): string { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
async function main(): Promise<void> {
  const client = await new MongoClient(process.env.MONGODB_URI ?? DEFAULT_URI, { serverSelectionTimeoutMS: 5_000 }).connect(); const startedAt = new Date(); const runId = `run_verified_20260510_16_${startedAt.toISOString().replace(/\D/g, "").slice(0, 14)}_${randomUUID().slice(0, 8)}`; const counts = { downloaded: 3, new: 0, updated: 0, duplicate: 0, failed: 0 }; const db = client.db(process.env.MONGODB_DB ?? "palantir_th");
  try {
    const source: SourceRegistryDoc = { _id: SOURCE_ID, name: "Palantir TH manual research ledger", shortName: "Manual research", category: "research", priority: "P3", role: "Manually corroborated event enrichment", connector: { type: "FORM" }, schedule: { mode: "snapshot", frequency: "manual" }, trust: { class: "manual_entry", score: 60 }, enabled: true };
    await db.collection<SourceRegistryDoc>("source_registry").updateOne({ _id: SOURCE_ID }, { $setOnInsert: source }, { upsert: true }); const run: IngestionRunDoc = { _id: runId, source_id: SOURCE_ID, started_at: startedAt, finished_at: null, status: "running", records: counts }; await db.collection<IngestionRunDoc>("ingestion_runs").insertOne(run);
    const payload = { record_type: "manual_research_enrichment", window_id: WINDOW_ID, candidate_id: update.id, sources: update.urls, normalized_update: update.set }; const rawId = `raw_manual_enrichment_${WINDOW_ID}_${update.id}`; const raw: RawRecordDoc = { _id: rawId, source_id: SOURCE_ID, external_id: `${WINDOW_ID}-enrichment-${update.id}`, retrieved_at: startedAt, source: { url: update.urls[0] }, dataset: { name: "Palantir TH verified event window", version: WINDOW_ID }, raw: payload, integrity: { content_hash: `sha256:${hash(payload)}`, algorithm: "sha256" }, processing: { status: "normalized" }, ingestion_run_id: runId };
    await db.collection<RawRecordDoc>("raw_records").updateOne({ _id: rawId }, { $setOnInsert: raw }, { upsert: true }); const sourceAttrs = Object.fromEntries(update.urls.map((url, i) => [`attributes.source_url_${i + 1}`, url])); const set = { ...update.set, ...sourceAttrs, "attributes.research_batch": WINDOW_ID, "attributes.enrichment_raw_record_id": rawId, "attributes.location_address": update.set["location.place"], "attributes.source_count": update.urls.length }; const updated = await db.collection<EventCandidateDoc>("event_candidates").updateOne({ _id: update.id }, { $set: set as never, $addToSet: { corroborating_sources: SOURCE_ID }, $pull: { unreported: { $in: ["severity", "casualties", "casualties.killed", "casualties.injured", "actors", "targets", "exact_time"] } } }); if (!updated.matchedCount) throw new Error(`Existing candidate ${update.id} was not found`); updated.modifiedCount ? counts.updated++ : counts.duplicate++;
    for (const candidate of additions) { const urls = Object.entries(candidate.attributes).filter(([key]) => key.startsWith("source_url_")).map(([, value]) => String(value)); const claim = { record_type: "manual_research_claim", window_id: WINDOW_ID, candidate, sources: urls }; const record: RawRecordDoc = { _id: candidate.raw_record_id, source_id: SOURCE_ID, external_id: `${WINDOW_ID}-${candidate._id}`, retrieved_at: startedAt, source: { url: urls[0] }, dataset: { name: "Palantir TH verified event window", version: WINDOW_ID }, raw: claim, integrity: { content_hash: `sha256:${hash(claim)}`, algorithm: "sha256" }, processing: { status: "normalized" }, ingestion_run_id: runId }; await db.collection<RawRecordDoc>("raw_records").updateOne({ _id: record._id }, { $setOnInsert: record }, { upsert: true }); const result = await db.collection<EventCandidateDoc>("event_candidates").updateOne({ _id: candidate._id }, { $setOnInsert: candidate }, { upsert: true }); result.upsertedCount ? counts.new++ : counts.duplicate++; }
    const halal = additions[1]; const correctionPayload = { record_type: "manual_research_correction", window_id: WINDOW_ID, candidate_id: halal._id, supersedes_raw_record_id: halal.raw_record_id, reason: "device status was not fully enumerated by the source", normalized_update: { "event.summary": halal.event.summary, "attributes.exploded_device_count_minimum": 3, "attributes.device_status_unresolved_count": 5 } }; const correctionId = `raw_manual_correction_${WINDOW_ID}_${halal._id}_device_status`; const correction: RawRecordDoc = { _id: correctionId, source_id: SOURCE_ID, external_id: `${WINDOW_ID}-${halal._id}-device-status-correction`, retrieved_at: startedAt, source: { url: String(halal.attributes.source_url_2) }, dataset: { name: "Palantir TH verified event window", version: WINDOW_ID }, raw: correctionPayload, integrity: { content_hash: `sha256:${hash(correctionPayload)}`, algorithm: "sha256" }, processing: { status: "normalized" }, ingestion_run_id: runId }; await db.collection<RawRecordDoc>("raw_records").updateOne({ _id: correctionId }, { $setOnInsert: correction }, { upsert: true }); await db.collection<EventCandidateDoc>("event_candidates").updateOne({ _id: halal._id }, { $set: { "event.summary": halal.event.summary, "attributes.exploded_device_count_minimum": 3, "attributes.device_status_unresolved_count": 5, "attributes.device_count_discrepancy": halal.attributes.device_count_discrepancy, "attributes.device_status_correction_raw_record_id": correctionId }, $unset: { "attributes.exploded_device_count": "" } });
    await db.collection<IngestionRunDoc>("ingestion_runs").updateOne({ _id: runId }, { $set: { finished_at: new Date(), status: "success", records: counts } }); console.log(JSON.stringify({ runId, window: WINDOW_ID, counts }, null, 2));
  } catch (error) { await db.collection<IngestionRunDoc>("ingestion_runs").updateOne({ _id: runId }, { $set: { finished_at: new Date(), status: "failed", error: error instanceof Error ? error.message : String(error), records: { ...counts, failed: 1 } } }); throw error; } finally { await client.close(); }
}
main().catch((error) => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
