/** Enrich verified southern security incidents for 31 May-6 Jun 2026. */
import { createHash, randomUUID } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { MongoClient } from "mongodb";
import type { EventCandidateDoc, IngestionRunDoc, RawRecordDoc, SourceRegistryDoc } from "../src/lib/types";
function loadEnv(): void { const p = resolve(process.cwd(), ".env"); if (!existsSync(p)) return; for (const line of readFileSync(p, "utf8").split(/\r?\n/)) { const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/); if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^(['"])(.*)\1$/, "$2"); } }
loadEnv();
const SOURCE_ID = "src_manual_research", WINDOW_ID = "verified-window-2026-05-31-to-06-06", DEFAULT_URI = "mongodb://root:changeme@localhost:27017/palantir_th?authSource=admin", SBPAC = "https://opendata.sbpac.go.th/API/relief_01_01.aspx";
const updates: Array<{ id: string; urls: string[]; set: Record<string, unknown> }> = [
  { id: "evt_60a1b102a100e425ecad4927", urls: ["https://www.isranews.org/article/south-news/south-slide/147281-padisub.html", "https://suhaipadee.narathiwat.police.go.th/ตรวจสถานที่เกิดเหตุคนร-2/", SBPAC], set: {
    "time.start": new Date("2026-06-04T00:00:00+07:00"), "time.precision": "day", "location.place": "ถนนสายปะลุรู–สุไหงปาดี บริเวณบ้านปะลุรู หมู่ 3 ตำบลปะลุรู อำเภอสุไหงปาดี จังหวัดนราธิวาส", "location.geo": null, "location.geo_precision": "unknown",
    "event.type": "shooting", "event.title": "ซุ่มยิงสมาชิก อส.บนถนนปะลุรู–สุไหงปาดี", "event.rawType": "ลอบยิงเจ้าหน้าที่กองอาสารักษาดินแดน", "event.summary": "กลุ่มคนร้ายใช้อาวุธปืนสงครามซุ่มยิงสมาชิกเอก อุรุพงษ์ กมล อายุ 35 ปี สังกัด อส.อำเภอสุไหงปาดีที่ 9 ขณะขี่รถจักรยานยนต์บนถนนสายปะลุรู–สุไหงปาดี กระสุนถูกลำตัวหลายนัด ทหารพรานที่ผ่านมาช่วยนำส่งโรงพยาบาล ก่อนเสียชีวิตจากบาดแผลและการเสียเลือด", severity: 5, verification: "verified", confidence: 98, casualties: { killed: 1, injured: 0 }, actors: ["กลุ่มมือปืนไม่ทราบจำนวน"], targets: ["สมาชิกเอก อุรุพงษ์ กมล อส.ชคต.สุไหงปาดี"], "attributes.weapon_evidence": "ปลอกกระสุนเอ็ม 16 อาก้า และลูกซอง", "attributes.location_text_precision": "road_village",
  } },
  { id: "evt_d1c92b1e0b41ddbe4c6e58ee", urls: ["https://www.isranews.org/article/south-news/other-news/147244-kokphofight.html", "https://workpointnews.com/news/crime/NkCzOQQYy", SBPAC], set: {
    "time.start": new Date("2026-06-04T00:00:00+07:00"), "time.precision": "day", "location.place": "บ้านเป้าหมาย บ้านท่าคลอง หมู่ 10 ตำบลโคกโพธิ์ อำเภอโคกโพธิ์ จังหวัดปัตตานี", "location.geo": null, "location.geo_precision": "unknown",
    "event.type": "raid", "event.title": "ปิดล้อมปะทะผู้ต้องสงสัยคดีความมั่นคงที่บ้านท่าคลอง", "event.rawType": "ปฏิบัติการบังคับใช้กฎหมายและยิงปะทะ", "event.summary": "เจ้าหน้าที่สนธิกำลังปิดล้อมบ้านเป้าหมายหลังได้รับเบาะแสผู้ต้องสงสัยคดีความมั่นคง พยายามเจรจาหลายชั่วโมงแต่บุคคลในบ้านยิงและขว้างวัตถุระเบิดเพื่อเปิดทางหนี จึงเกิดการยิงตอบโต้ ผู้ต้องสงสัยเสียชีวิต 2 ราย เจ้าหน้าที่บาดเจ็บเล็กน้อย 1 นาย ยึดปืนพก 2 กระบอกและไปป์บอมบ์ 1 ลูก", severity: 5, verification: "verified", confidence: 98, casualties: { killed: 2, injured: 1 }, actors: ["เจ้าหน้าที่ทหาร ตำรวจ ฝ่ายปกครอง และ นปพ.ร่วม", "ผู้ต้องสงสัยติดอาวุธ 2 ราย"], targets: ["บ้านเป้าหมายและผู้ต้องสงสัยคดีความมั่นคง", "เจ้าหน้าที่บังคับใช้กฎหมาย"], "attributes.seized_firearms": 2, "attributes.seized_pipe_bombs": 1, "attributes.location_text_precision": "village_residence",
  } },
  { id: "evt_09ab1f563e83e37a9b1551d0", urls: ["https://www.thaipbs.or.th/news/content/506758", "https://isranews.org/article/south-slide/147293-thantobpp.html", SBPAC], set: {
    "time.start": new Date("2026-06-05T00:00:00+07:00"), "time.precision": "day", "location.place": "ฐานปฏิบัติการด่านตรวจร่วม 3 ฝ่าย หน้าตลาดธารโต ใกล้ที่ทำการนิคมสร้างตนเองธารโต ตำบลธารโต อำเภอธารโต จังหวัดยะลา", "location.geo": null, "location.geo_precision": "unknown",
    "event.type": "shooting", "event.title": "ซุ่มยิง ตชด.หน้าฐานปฏิบัติการตลาดธารโต", "event.rawType": "ลอบยิงตำรวจตระเวนชายแดน", "event.summary": "คนร้ายซุ่มยิงจากด้านหลังอาคารที่ทำการนิคมสร้างตนเองธารโต ใส่เจ้าหน้าที่ ตชด.ชุดปฏิบัติการ 4411 ขณะอยู่บริเวณฐานด่านตรวจร่วม 3 ฝ่ายหน้าตลาดธารโตในช่วงค่ำ ส.ต.ท.กันตวิชญ์ นาคเกิด ถูกกระสุนบริเวณหัวไหล่ขวา 1 นัดและถูกนำส่งโรงพยาบาล", severity: 4, verification: "verified", confidence: 97, casualties: { killed: 0, injured: 1 }, actors: ["มือปืนไม่ทราบกลุ่มและจำนวน"], targets: ["ส.ต.ท.กันตวิชญ์ นาคเกิด ตชด.4411", "ฐานปฏิบัติการด่านตรวจร่วม 3 ฝ่าย"], "attributes.reported_time_text": "ช่วงค่ำ", "attributes.location_text_precision": "named_site",
  } },
];
function hash(v: unknown): string { return createHash("sha256").update(JSON.stringify(v)).digest("hex"); }
async function main(): Promise<void> { const client = await new MongoClient(process.env.MONGODB_URI ?? DEFAULT_URI).connect(); const startedAt = new Date(), runId = `run_verified_20260531_0606_${startedAt.toISOString().replace(/\D/g, "").slice(0, 14)}_${randomUUID().slice(0, 8)}`, counts = { downloaded: 3, new: 0, updated: 0, duplicate: 0, failed: 0 }; const db = client.db(process.env.MONGODB_DB ?? "palantir_th"); try {
  const source: SourceRegistryDoc = { _id: SOURCE_ID, name: "Palantir TH manual research ledger", shortName: "Manual research", category: "research", priority: "P3", role: "Manually corroborated event enrichment", connector: { type: "FORM" }, schedule: { mode: "snapshot", frequency: "manual" }, trust: { class: "manual_entry", score: 60 }, enabled: true }; await db.collection<SourceRegistryDoc>("source_registry").updateOne({ _id: SOURCE_ID }, { $setOnInsert: source }, { upsert: true }); const run: IngestionRunDoc = { _id: runId, source_id: SOURCE_ID, started_at: startedAt, finished_at: null, status: "running", records: counts }; await db.collection<IngestionRunDoc>("ingestion_runs").insertOne(run);
  for (const item of updates) { const payload = { record_type: "manual_research_enrichment", window_id: WINDOW_ID, candidate_id: item.id, sources: item.urls, normalized_update: item.set }, rawId = `raw_manual_enrichment_${WINDOW_ID}_${item.id}`; const raw: RawRecordDoc = { _id: rawId, source_id: SOURCE_ID, external_id: `${WINDOW_ID}-${item.id}`, retrieved_at: startedAt, source: { url: item.urls[0] }, dataset: { name: "Palantir TH verified event window", version: WINDOW_ID }, raw: payload, integrity: { content_hash: `sha256:${hash(payload)}`, algorithm: "sha256" }, processing: { status: "normalized" }, ingestion_run_id: runId }; await db.collection<RawRecordDoc>("raw_records").updateOne({ _id: rawId }, { $setOnInsert: raw }, { upsert: true }); const sourceAttrs = Object.fromEntries(item.urls.map((url, i) => [`attributes.source_url_${i + 1}`, url])); const result = await db.collection<EventCandidateDoc>("event_candidates").updateOne({ _id: item.id }, { $set: { ...item.set, ...sourceAttrs, "attributes.research_batch": WINDOW_ID, "attributes.enrichment_raw_record_id": rawId, "attributes.location_address": item.set["location.place"], "attributes.source_count": item.urls.length } as never, $addToSet: { corroborating_sources: SOURCE_ID }, $pull: { unreported: { $in: ["severity", "casualties", "actors", "targets"] } } }); if (!result.matchedCount) throw new Error(`Missing ${item.id}`); result.modifiedCount ? counts.updated++ : counts.duplicate++; }
  await db.collection<IngestionRunDoc>("ingestion_runs").updateOne({ _id: runId }, { $set: { finished_at: new Date(), status: "success", records: counts } }); console.log(JSON.stringify({ runId, window: WINDOW_ID, counts }, null, 2));
} catch (e) { await db.collection<IngestionRunDoc>("ingestion_runs").updateOne({ _id: runId }, { $set: { finished_at: new Date(), status: "failed", error: e instanceof Error ? e.message : String(e), records: { ...counts, failed: 1 } } }); throw e; } finally { await client.close(); } }
main().catch((e) => { console.error(e); process.exitCode = 1; });
